defaults: &defaults
  working_directory: ~/project/repo
  docker:
    - image: circleci/node:latest

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
          - v1-dependencies-{{ .Branch }}-
          - v1-dependencies-
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-npm-dependencies
          command: 'npm ci'
      - save_cache:
          key: v1-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - $HOME/.npm
      - run:
          name: test
          command: 'npm test'
      - persist_to_workspace:
          root: ~/project
          paths:
            - repo
  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: .circleci/setup-git.sh > /dev/null 2>&1
      - run: npx semantic-release

workflows:
  version: 2
  test_and_release:
    jobs:
      - test
      - release:
          context: Release
          requires:
            - test
